### ISSUE TITLE
"feature_names" should be optional

### ISSUE THREAD

**Issue by FrankKr** [OpenSTEF/openstf#154]
https://github.com/alliander-opensource/openstf/blob/e72b75bb1508e2a74e47885215b91070a96e4774/openstf/pipeline/train_model.py#L206

The 'feature_names' attribute of prediction_job should be optional. Change this line so it uses pj.get("feature_names") instead.

**Comment by Davidswinkels** [comment]
In latest implementation feature names are not retrieved from prediction job anymore. Therefore this issue is solved :)
