### ISSUE TITLE
Multiple reference implementations

### ISSUE THREAD

**Issue by Sander3003** [OpenSTEF/openstf#240]
The Readme.md states:
A complete implementation including databases, user interface, example data, etc. is available at: 
https://github.com/alliander-opensource/openstf-reference

Their is also an open source one:
https://github.com/OpenSTEF/openstef-reference

What is the difference?

**Comment by FrankKr** [comment]
Both link to the same repository (which was transitioned between github organisations). I'll update the readme, thanks for noticing.
